addresses/urls.py
from django.urls import path

from addresses.apps import AddressesConfig
from addresses.views import AddressCreateView, AddressListView, AddressDetailView, AddressUpdateView, AddressDeleteView, \
    toggle_activity

app_name = AddressesConfig.name

urlpatterns = [
    path('create/', AddressCreateView.as_view(), name='create'),
    path('', AddressListView.as_view(), name='list'),
    path('view/<int:pk>/', AddressDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', AddressUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', AddressDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('addresses/', include('addresses.urls', namespace='addresses')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, EmailSentView, EmailConfirmedView, EmailConfirmedFailedView, \
    ConfirmFromEmailView, UserNotFound, UserPasswordResetView

app_name = UsersConfig.name



urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm_from_email/<str:uidb64>/<str:token>/', ConfirmFromEmailView.as_view(), name='confirm_from_email'),
    path('email_sent/', EmailSentView.as_view(), name='email_sent'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmed_failed/', EmailConfirmedFailedView.as_view(), name='email_confirmed_failed'),
    path('not_found', UserNotFound.as_view(), name='not_found'),
    path('password_reset', UserPasswordResetView.as_view(), name='password_reset'),
]

addresses/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Address(models.Model):
    """ Модель адрес """
    title = models.CharField(max_length=150, verbose_name='название магазина')
    location = models.TextField(verbose_name='местоположение')
    image = models.ImageField(upload_to='address/', **NULLABLE)
    date_of_creation = models.DateField(auto_now_add=False, verbose_name='Дата создания', **NULLABLE, help_text='В формате "дд.мм.гггг"')

    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры', editable=False)
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)



    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'адрес'
        verbose_name_plural = 'адреса'
        ordering = ['-date_of_creation', 'title']

addresses/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from addresses.models import Address


class AddressCreateView(CreateView):
    """Класс для создания адреса"""
    model = Address
    fields = ('title', 'location', 'date_of_creation', 'is_published', 'image')
    success_url = reverse_lazy('addresses:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save(commit=False)
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

class AddressUpdateView(UpdateView):
    """Класс для изменения адреса"""
    model = Address
    fields = ('title', 'location', 'image', 'date_of_creation', 'is_published')
    # success_url = reverse_lazy('addresses:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save(commit=False)
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('addresses:view', args=[self.kwargs.get('pk')])

class AddressListView(ListView):
    """Класс для вывода всех адресов"""
    model = Address
    extra_context = {"title": "Адреса магазинов"}

    def get_queryset(self, *args, **kwargs):
        """ Метод для определения актуальных адресов"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

class AddressDetailView(DetailView):
    """Класс для вывода информации об адресе по его pk"""
    model = Address

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

class AddressDeleteView(DeleteView):
    """Класс для удаления адреса"""
    model = Address
    success_url = reverse_lazy('addresses:list')


def toggle_activity(request, pk):
    address_item = get_object_or_404(Address, pk=pk)
    if address_item.is_published:
        address_item.is_published = False
    else:
        address_item.is_published = True

    address_item.save()

    return redirect(reverse('addresses:list'))

addresses/templates/addresses/address_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить магазин "{{ object.title }}" по адресу: {{ object.location }}?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'addresses:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

addresses/templates/addresses/address_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12 mb-5">
  <a class="btn btn-outline-dark" href="{% url 'addresses:list' %}">Назад к списку магазинов</a>
</div>
<div class="col-12">
    <div class="row">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Магазин "{{ object.title }}" ({{ object.slug }})
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Местоположение</td>
                            <td>{{ object.location }}</td>
                        </tr>
                        <tr>
                            <td>Дата размещения</td>
                            <td>{{ object.date_of_creation }}</td>
                        </tr>
                    </table>

                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'addresses:edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-warning">Изменить</a>
                            <a href="{% url 'addresses:delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-6">
            <img src="/media/{{ object.image }}"/>
        </div>
    </div>
</div>
{% endblock %}

addresses/templates/addresses/address_form.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12 mb-5">
  <a class="btn btn-outline-dark" href="{% url 'addresses:list' %}">Назад к списку магазинов</a>
</div>
    <div class="col-12">
        <div class="row">
            <div class="col-7">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

addresses/templates/addresses/address_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-success" href="{% url 'addresses:create' %}">Добавить адрес</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 src="{{ object.image|mymedia }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">
                    {% if object.is_published %}
                    {{ object|title }}
                    {% else %}
                    <span class="text-muted">{{ object|title }}</span>
                    {% endif %}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'addresses:view' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-info">Посмотреть</a>
                        <a href="{% url 'addresses:edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-warning">Изменить</a>
                        <a href="{% url 'addresses:delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-danger">Удалить</a>
                    </div>
                    {% if object.is_published %}
                    <a class="btn btn-warning" href="{% url 'addresses:toggle_activity' object.pk %}">X</a>
                    {% else %}
                    <a class="btn btn-success" href="{% url 'addresses:toggle_activity' object.pk %}">V</a>
                    {% endif %}
                </div>

                <tr>
                    <td>Просмотры: {{ object.views_count }}</td>
                </tr>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}