config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('addresses/', include('addresses.urls', namespace='addresses')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, EmailSentView, EmailConfirmedView, EmailConfirmedFailedView, \
    ConfirmFromEmailView, UserNotFound, UserPasswordResetView

app_name = UsersConfig.name



urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm_from_email/<str:uidb64>/<str:token>/', ConfirmFromEmailView.as_view(), name='confirm_from_email'),
    path('email_sent/', EmailSentView.as_view(), name='email_sent'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmed_failed/', EmailConfirmedFailedView.as_view(), name='email_confirmed_failed'),
    path('not_found', UserNotFound.as_view(), name='not_found'),
    path('password_reset', UserPasswordResetView.as_view(), name='password_reset'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='страна', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import Form, EmailField

from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

class ResetForm(Form):
    email = EmailField()

users/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView, FormView

from users.forms import UserRegisterForm, UserProfileForm, ResetForm
from users.models import User


class RegisterView(CreateView):
    """ Класс для регистрации пользователя."""
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """ Переопределение метода для верификации почты."""
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse('users:confirm_from_email', kwargs={'uidb64': uid, 'token': token})

        send_mail(
            'Подтвердите адрес электронной почты',
            f'Для окончания регистрации необходимо подтвердить вашу электронную почту.\
            Чтобы это сделать, перейдите по ссылке: http://localhost:8000{activation_url}',
            settings.EMAIL_HOST_USER,
            [user.email],
            fail_silently=False
        )

        return redirect('users:email_sent')

class EmailSentView(TemplateView):
    """ Класс для отображения отправки письма. """
    template_name = 'users/email_sent.html'

class ConfirmFromEmailView(View):
    """ Класс для обработки ссылки подтверждения. """
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')
        return redirect('users:email_confirmed_failed')

class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'

class EmailConfirmedFailedView(TemplateView):
    template_name = 'users/email_confirmed_failed.html'

class UserPasswordResetView(FormView):
    """ Класс восстановление пароля. """
    template_name = 'users/password_reset_form.html'
    form_class = ResetForm


    def form_valid(self, form):
        email = form.cleaned_data['email']
        try:
            user = User.objects.get(email=email)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None:
            new_password = User.objects.make_random_password(length=8)
            user.set_password(new_password)
            user.save()
            send_mail(
            'Ваш новый пароль.',
            f'Для входа используйте новый пароль: {new_password}.',
            settings.EMAIL_HOST_USER,
            [user.email],
            fail_silently=False
        )
            return redirect('users:email_sent')
        return redirect('users:not_found')

class UserNotFound(TemplateView):
    template_name = 'users/not_found.html'

class ProfileView(UpdateView):
    """ Класс редактирования профиля пользователя. """
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/email_confirmed.html
{% extends 'catalog/home.html' %}

{% block content %}

<div class="card-header">
    <h3 class="card-title">
        Email подтвержден.
    </h3>
</div>

{% endblock %}

users/templates/users/email_confirmed_failed.html
{% extends 'catalog/home.html' %}

{% block content %}

<div class="card-header">
    <h3 class="card-title">
        Email не подтвержден. Попробуйте снова.
    </h3>
</div>

{% endblock %}

users/templates/users/email_sent.html
{% extends 'catalog/home.html' %}

{% block content %}

<div class="card-header">
    <h3 class="card-title">
        Письмо отправлено.
    </h3>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-7">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Войти</button>
                        <a href="{% url 'users:password_reset' %}" class="btn btn-warning">Восстановить пароль</a>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/not_found.html
{% extends 'catalog/home.html' %}

{% block content %}

<div class="card-header">
    <h3 class="card-title">
        Пользователь не найден или почта введена неверно. Проверьте правильность написания и попробуйте снова.
    </h3>
</div>

{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-7">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Восстановление пароля
                    </h3>
                </div>
                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Восстановить пароль</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-7">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-7">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Профиль
                    </h3>
                </div>
                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}