addresses/urls.py
from django.urls import path

from addresses.apps import AddressesConfig
from addresses.views import AddressCreateView, AddressListView, AddressDetailView, AddressUpdateView, AddressDeleteView, \
    toggle_activity

app_name = AddressesConfig.name

urlpatterns = [
    path('create/', AddressCreateView.as_view(), name='create'),
    path('', AddressListView.as_view(), name='list'),
    path('view/<int:pk>/', AddressDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', AddressUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', AddressDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

catalog/urls.py
from django.urls import path

from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import home, contacts, index, categories, category_products, ProductDetailView, ProductListView, \
    ProductCreateView, ProductUpdateView, ProductDeleteView, VersionListView, VersionCreateView, VersionUpdateView, \
    VersionDetailView, VersionDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('categories/', categories, name='categories'),
    path('<int:pk>products/', category_products, name='category_products'),
    path('contacts/', contacts, name='contacts'),
    path('products/', ProductListView.as_view(), name='products'),
    path('view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('versions/<int:pk>', VersionListView.as_view(), name='versions'),
    path('versions/create/<int:pk>', VersionCreateView.as_view(), name='version_create'),
    path('versions/edit/<int:pk>/', VersionUpdateView.as_view(), name='version_edit'),
    path('versions/view/<int:pk>/', VersionDetailView.as_view(), name='version_view'),
    path('versions/delete/<int:pk>/', VersionDeleteView.as_view(), name='version_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('addresses/', include('addresses.urls', namespace='addresses')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, EmailSentView, EmailConfirmedView, EmailConfirmedFailedView, \
    ConfirmFromEmailView, UserNotFound, UserPasswordResetView

app_name = UsersConfig.name



urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm_from_email/<str:uidb64>/<str:token>/', ConfirmFromEmailView.as_view(), name='confirm_from_email'),
    path('email_sent/', EmailSentView.as_view(), name='email_sent'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmed_failed/', EmailConfirmedFailedView.as_view(), name='email_confirmed_failed'),
    path('not_found', UserNotFound.as_view(), name='not_found'),
    path('password_reset', UserPasswordResetView.as_view(), name='password_reset'),
]

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    """ Модель для категории """
    name = models.CharField(max_length=100, verbose_name='Категория')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    """
    Модель для продукта относящегося к категории по ключу ForeignKey.
    """
    name = models.CharField(max_length=200, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='product/', **NULLABLE)
    # category = models.CharField(max_length=100, verbose_name='Категория')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', help_text='Выберите категорию')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    date_of_creation = models.DateField(auto_now_add=False, verbose_name='Дата изготовления', **NULLABLE, help_text='В формате "дд.мм.гггг"')
    last_modified_date = models.DateField(**NULLABLE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    is_published = models.BooleanField(default=False, verbose_name='опубликовано')

    def __str__(self):
        return f'{self.name}: {self.price}  ({self.category})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('category',)
        permissions = [
            ('can_publish', 'Право доступа для публикации')
        ]

class Version(models.Model):
    """ Модель для версии продукта """
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number = models.PositiveIntegerField(verbose_name='номер версии')
    name = models.CharField(max_length=150, verbose_name='название версии')
    current_version = models.BooleanField(default=True, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.forms import HiddenInput

from catalog.models import Version, Product


class StyleForMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleForMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'price', 'date_of_creation', 'image')



    def clean_name(self):
        """
        Метод для проверки поля 'name',
        на наличие слова из списка исключений.
        """
        name = self.cleaned_data.get('name')
        words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in words:
            if word in name:
                raise forms.ValidationError(f'Запрещенное слово "{word}" в названии товара.')

        return name

    def clean_description(self):
        """
        Метод для проверки поля 'description',
        на наличие слова из списка исключений.
        """
        description = self.cleaned_data.get('description')
        words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in words:
            if word in description:
                raise forms.ValidationError(f'Запрещенное слово "{word}" в описании товара.')

        return description


class VersionForm(StyleForMixin, forms.ModelForm):
    class Meta:
        widgets = {'product': HiddenInput()}
        model = Version
        fields = '__all__'

    def clean_current_version(self):
        """ Метод для проверки наличия активной версии. """
        product = self.cleaned_data.get('product')
        current_version = self.cleaned_data.get('current_version')
        if current_version:
            if Version.objects.filter(current_version=True, product=product).exclude(pk=product.pk).exists():
                raise forms.ValidationError('Активная версия уже существует.')
        return current_version

    def clean_number(self):
        """ Метод для проверки уникальности номера версии. """
        product = self.cleaned_data.get('product')
        clean_number = self.cleaned_data.get('number')
        if self.instance is not None:
            if Version.objects.filter(number=clean_number, product=product).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('Версия с таким номером уже существует.')
        return clean_number

catalog/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import VersionForm, ProductForm
from catalog.models import Category, Product, Version
from services.catalog import get_categories


@login_required
@permission_required('catalog.view_product')
def home(request):
    return render(request, 'catalog/home.html')


@login_required
@permission_required('catalog.view_product')
def index(request):
    context = {
        'object_list': Category.objects.all(),
        'title': 'Магазин - Продукты'
    }
    return render(request, 'catalog/index.html', context)

@login_required
def categories(request):
    context = {
        'object_list': get_categories(),
        'title': 'Магазин - Категории'
    }
    return render(request, 'catalog/categories.html', context)

@login_required
@permission_required('catalog.view_product')
def category_products(request, pk):
    category_item = get_categories().get(pk=pk)
    context = {
        'object_list': Product.objects.filter(category_id=pk),
        'title': f'Продукты категории "{category_item.name}"'
    }
    return render(request, 'catalog/products.html', context)

class ProductListView(LoginRequiredMixin, ListView):
    """Класс для вывода списка продуктов"""
    model = Product
    template_name = 'catalog/products.html'
    extra_context = {"title": "Продукты"}

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["Продукты"] = Product.objects.all()
    #     context["title"] = "Продукты"
    #     return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    """Класс для вывода информации о продукте по его pk"""
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = self.model.objects.filter(pk=self.kwargs.get('pk'))
        context["title"] = self.object.name
        return context


def contacts(request):
    context = {
        'title': 'Контакты'
    }
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} {phone}: {message}')
    return render(request, 'catalog/contacts.html', context)

class ProductCreateView(LoginRequiredMixin, CreateView):
    """ Класс для создания продукта. """
    model = Product
    form_class = ProductForm
    # fields = ('name', 'description', 'category', 'price', 'date_of_creation', 'image')
    success_url = reverse_lazy('catalog:products')
    def form_valid(self, form):
        product = form.save(commit=False)
        product.user = self.request.user
        product.save()
        return redirect(self.success_url)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """ Класс для редактирования продукта. """
    model = Product
    fields = ('name', 'description', 'category', 'price', 'date_of_creation', 'image')
    success_url = reverse_lazy('catalog:products')


    def get_object(self, queryset=None):
        """ Переопределение метода для проверки принадлежности и прав доступа """
        obj = super().get_object(queryset)
        perms = ['product.change_product', 'product.can_publish']
        if obj.user == self.request.user or self.request.user.has_perms(perms):
            return obj
        raise PermissionDenied

class ProductDeleteView(LoginRequiredMixin, DeleteView):
    """ Класс для удаления продукта. """
    model = Product
    success_url = reverse_lazy('catalog:products')

    def get_object(self, queryset=None):
        """ Переопределение метода для проверки принадлежности и прав доступа """
        obj = super().get_object(queryset)
        perms = ['product.delete_product']
        if obj.user == self.request.user or self.request.user.has_perms(perms):
            return obj
        raise PermissionDenied


class VersionListView(LoginRequiredMixin, ListView):
    """Класс для вывода списка версий определенного продукта"""
    model = Version
    extra_context = {"title": "Версии"}

    def get_queryset(self, *args, **kwargs):
        return Version.objects.filter(product=Product.objects.get(pk=self.kwargs.get('pk')))

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(object_list=object_list, **kwargs)
        context_data['pk'] = self.kwargs.get('pk')
        # context_data['object_list'] = self.model.objects.filter(pk=self.kwargs.get('pk'))
        return context_data

class VersionCreateView(LoginRequiredMixin, CreateView):
    """Класс для создания версии"""
    model = Version
    form_class = VersionForm
    # success_url = reverse_lazy('catalog:versions')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.initial = {'product': Product.objects.get(pk=self.kwargs.get('pk'))}
        return form

    def get_success_url(self):
        return reverse('catalog:versions', kwargs={'pk': self.object.product.pk})

    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     self.object.product = Product.objects.get(pk=self.kwargs.get('pk'))
    #     self.object.save()
    #     return HttpResponseRedirect(self.get_success_url())

class VersionUpdateView(LoginRequiredMixin, UpdateView):
    """Класс для редактирования версии. """
    model = Version
    form_class = VersionForm
    # success_url = reverse_lazy('catalog:versions')
    def get_success_url(self):
        return reverse('catalog:versions', kwargs={'pk': self.object.product.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.object.product.pk
        return context

class VersionDetailView(LoginRequiredMixin, DetailView):
    """ Класс для вывода информации о версии по его pk"""
    model = Version

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.object.product.pk
        return context

class VersionDeleteView(LoginRequiredMixin, DeleteView):
    """Класс для удаления версии"""
    model = Version
    # success_url = reverse_lazy('catalog:versions')

    def get_success_url(self):
        return reverse('catalog:versions', kwargs={'pk': self.object.product.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.object.product.pk
        return context

catalog/templates/catalog/categories.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
        {% include 'catalog/includes/inc_category.html' %}
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/home.html' %}

{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>(495) 555-55-55</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Москва, Петровка, 2</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-5 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Введите сообщение" required></textarea>
                        </div>
                        <input type="submit" class="btn btn-lg btn-block btn-outline-dark"/>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">Интернет-магазин свежих продуктов</h4>
              <p class="text-muted">Мы работаем, чтобы вы могли готовить дома блюда из продуктов ресторанного качества.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Меню</h4>
              <ul class="list-unstyled">
                <li><a href="{% url 'catalog:index' %}" class="text-white">Главная</a></li>
                <li><a href="{% url 'catalog:categories' %}" class="text-white">Категории</a></li>
                <li><a href="{% url 'catalog:products' %}" class="text-white">Все товары</a></li>
                <li><a href="{% url 'addresses:list' %}" class="text-white">Адреса магазинов</a></li>
                <li><a href="{% url 'catalog:contacts' %}" class="text-white">Контакты</a></li>
                {% if user.is_authenticated %}
                  <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                  <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
                {% else %}
                  <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                  <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'catalog:products' %}" class="navbar-brand d-flex align-items-center">
            <strong>Все товары</strong>
          </a>
          <a href="{% url 'catalog:categories' %}" class="navbar-brand d-flex align-items-center">
            <strong>Категории</strong>
          </a>
          <a href="{% url 'addresses:list' %}" class="navbar-brand d-flex align-items-center">
            <strong>Адреса магазинов</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
          {% block content %}
          {% endblock %}

        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>

      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

catalog/templates/catalog/index.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
        {% include 'catalog/includes/inc_category.html' %}
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12 mb-5">
  <a class="btn btn-outline-dark" href="{% url 'catalog:products' %}">Назад к продуктам</a>
</div>
  <div class="col-12">
    <div class="row">

      <div class="col-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              Информация о товаре
            </h3>
          </div>
          <div class="card-body">
            <table class="table">
              <tr>
                <td>Название</td>
                <td>{{ object.name }}</td>
              </tr>
              <tr>
                <td>Описание товара</td>
                <td>{{ object.description }}</td>
              </tr>
              <tr>
                <td>Цена</td>
                <td>{{ object.price }} ₽</td>
              </tr>
            </table>
            <div>
                    {% for version in object.version_set.all %}
                    {% if version.current_version %}
                    <p>Номер текущей версии: {{ version.number }}</p>
                    <p>Название текущей версии: {{ version.name }}</p>
                    {% endif %}
                    {% endfor %}
                </div>
          </div>
          <div class="card-footer">
            <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            {% if user == object.owner or perms.product.can_publish and perms.product.change_product %}
                                <a href="{% url 'catalog:edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-warning">Изменить</a>
                            {% endif %}
                            {% if perms.catalog.delete_product %}
                                <a href="{% url 'catalog:delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                            {% endif %}
                        </div>
                <a class="btn btn-outline-dark" href="{% url 'catalog:versions' object.pk %}">Версии</a>
                    </div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <img src="/media/{{ object.image }}" />
      </div>
    </div>
  </div>

{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-dark" href="{% url 'catalog:categories' %}">К категориям</a>
</div>
<div class="col-12 mb-5">
    {% if perms.catalog.add_product %}
        <a class="btn btn-success" href="{% url 'catalog:create' %}">Добавить продукт</a>
    {% endif %}
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 src="{{ object.image|mymedia }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.name|title }}</p>
                <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <div class="btn-group">
                        <a href="{% url 'catalog:view' object.pk %}"
                           class="btn btn-sm btn-outline-info">Посмотреть</a>
                        {% if user == object.owner or perms.product.can_publish and perms.product.change_product %}
                            <a href="{% url 'catalog:edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-warning">Изменить</a>
                        {% endif %}
                        {% if perms.catalog.delete_product %}
                            <a href="{% url 'catalog:delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-danger">Удалить</a>
                        {% endif %}
                    </div>
                </div>
                <div>
                    {% for version in object.version_set.all %}
                    {% if version.current_version %}
                    <p>Номер текущей версии: {{ version.number }}</p>
                    <p>Название текущей версии: {{ version.name }}</p>
                    {% endif %}
                    {% endfor %}
                </div>
                <a class="btn btn-outline-dark" href="{% url 'catalog:versions' object.pk %}">Посмотреть версии</a>

            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/version_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12 mb-5">
  <a class="btn btn-outline-dark" href="{% url 'catalog:versions' pk %}">Назад к версиям</a>
</div>
  <div class="col-12">
    <div class="row">

      <div class="col-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              Информация о версии "{{ object.name }}"
            </h3>
          </div>
          <div class="card-body">
            <table class="table">
              <tr>
                <td>Название:</td>
                <td>{{ object.name }}</td>
              </tr>
              <tr>
                <td>Номер версии:</td>
                <td>{{ object.number }}</td>
              </tr>
              <tr>
                <td>Признак текущей версии</td>
                <td>
                  {% if object.current_version %}
                  <span class="text-success">Текущая</span>
                  {% else %}
                  <span class="text-danger">Нетекущая</span>
                  {% endif %}
                </td>
              </tr>
            </table>

          </div>
          <div class="card-footer">
            <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'catalog:version_edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-warning">Изменить</a>
                            <a href="{% url 'catalog:version_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                        </div>
                    </div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <img src="/media/{{ object.image }}" />
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/version_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-dark" href="{% url 'catalog:view' pk %}">Назад к продукту</a>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-success" href="{% url 'catalog:version_create' pk %}">Добавить версию</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 src="{{ object.image|mymedia }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">Название версии: "{{ object.name|title }}"</p>
                <div>
                    <p>Номер версии: {{ object.number }}</p>
                </div>
                <div class="mb-4">
                    <td>Признак текущей версии</td>
                  {% if object.current_version %}
                  <span class="text-success">Текущая</span>
                  {% else %}
                  <span class="text-danger">Нетекущая</span>
                  {% endif %}
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:version_view' object.pk %}"
                           class="btn btn-sm btn-outline-info">Посмотреть</a>
                        <a href="{% url 'catalog:version_edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-warning">Изменить</a>
                        <a href="{% url 'catalog:version_delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-danger">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}